# Generated by Django 6.0.3 on 2026-04-04 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_property_to_shortlet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shortletimage',
            name='image',
            field=models.ImageField(upload_to='shortlets/'),
        ),
    ]
