# Generated by Django 6.0.3 on 2026-04-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortlet", "0003_update_shortlet_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortlet",
            name="base_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="shortlet",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="shortlet",
            name="title",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
