# Generated by Django 6.0.3 on 2026-04-05 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortlet", "0004_make_draft_fields_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortletHostAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("HOST", "Host"), ("COHOST", "Co-host")], max_length=10
                    ),
                ),
                ("can_edit", models.BooleanField(default=False)),
                ("can_upload_images", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortlet_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shortlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_assignments",
                        to="shortlet.shortlet",
                    ),
                ),
            ],
            options={
                "ordering": ["role"],
                "unique_together": {("shortlet", "role")},
            },
        ),
    ]
