# Generated by Django 6.0.3 on 2026-04-05 18:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortlet", "0005_shortlethostassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortlethostassignment",
            name="commission_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
    ]
