# Generated by Django 6.0.3 on 2026-04-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortlet", "0006_shortlethostassignment_commission_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "amenities",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="shortlet",
            name="amenities",
        ),
        migrations.AddField(
            model_name="shortlet",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="shortlets", to="shortlet.amenity"
            ),
        ),
    ]
