# Generated by Django 6.0.3 on 2026-04-05 19:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_booking_host_commission_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cohost_commission_percentage",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="cohost_payout_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
    ]
