# Generated by Django 6.0.3 on 2026-06-23 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_bookings", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=True)),
                ("email_reviews", models.BooleanField(default=True)),
                ("email_payouts", models.BooleanField(default=True)),
                ("email_marketing", models.BooleanField(default=False)),
                ("sms_booking_confirmations", models.BooleanField(default=True)),
                ("sms_security", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("push_bookings", models.BooleanField(default=True)),
                ("push_messages", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BOOKING_REQUESTED", "Booking requested"),
                            ("BOOKING_CONFIRMED", "Booking confirmed"),
                            ("BOOKING_CANCELLED", "Booking cancelled"),
                            ("BOOKING_COMPLETED", "Booking completed"),
                            ("REVIEW_RECEIVED", "Review received"),
                            ("REVIEW_REMINDER", "Review reminder"),
                            ("MESSAGE_RECEIVED", "Message received"),
                            ("INVITATION_RECEIVED", "Invitation received"),
                            ("PAYOUT_PROCESSED", "Payout processed"),
                            ("VERIFICATION_UPDATE", "Verification update"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("data", models.JSONField(blank=True, default=dict)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at"], name="notif_recipient_read_idx"
                    )
                ],
            },
        ),
    ]
