# Generated by Django 6.0.3 on 2026-04-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_identityverification_invitation_ownerhostmembership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identityverification",
            name="verification_type",
            field=models.CharField(
                choices=[("NIN", "National Identification Number")], max_length=3
            ),
        ),
    ]
